package com.dtc.transit.route.pattern;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;

import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;
import org.locationtech.jts.geom.LineString;

import com.dtc.transit.common.jpa.BaseEntity;
import com.dtc.transit.route.route.Direction;
import com.dtc.transit.route.route.Route;

/**
 * One directional path of a route, stored as a LineString.
 *
 * <p>Length and the projected copy are generated by the database, so they can never disagree with the
 * geometry they describe. Computing length in Java would also mean computing it in degrees, which is
 * meaningless as a distance.
 */
@Entity
@Table(name = "route_pattern")
public class RoutePattern extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "route_pattern_seq")
    @SequenceGenerator(name = "route_pattern_seq", sequenceName = "route_pattern_seq", allocationSize = 50)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "route_id", nullable = false)
    private Route route;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Direction direction;

    @Column(columnDefinition = "geometry(LineString,4326)", nullable = false)
    private LineString geom;

    /**
     * Length in metres, computed by the database in the projected CRS.
     *
     * <p>{@code @Generated} is what makes Hibernate re-read the column after an insert or update. Marking
     * it merely non-insertable leaves the field null in the returned entity, so a caller is told the route
     * has no length.
     */
    @Generated(event = {EventType.INSERT, EventType.UPDATE})
    @Column(name = "length_m", insertable = false, updatable = false)
    private Double lengthM;

    protected RoutePattern() {
        // for JPA
    }

    public RoutePattern(Route route, Direction direction, LineString geom) {
        this.route = route;
        this.direction = direction;
        this.geom = geom;
    }

    /** Replaces the geometry. Length is recomputed by the database on write. */
    public void replaceGeometry(LineString geom) {
        this.geom = geom;
    }

    public Long getId() {
        return id;
    }

    public Route getRoute() {
        return route;
    }

    public Direction getDirection() {
        return direction;
    }

    public LineString getGeom() {
        return geom;
    }

    /** Length in metres, computed in the projected CRS by the database. Null until first flush. */
    public Double getLengthM() {
        return lengthM;
    }
}
