package com.dtc.transit.masterdata.bus;

import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;

/**
 * A window in which a bus cannot run.
 *
 * <p>The two endpoints are mapped; the {@code period} range column is generated by the database and
 * deliberately not mapped here. That keeps range overlap tests as index-assisted SQL without needing a
 * custom Hibernate type for a PostgreSQL range.
 */
@Entity
@Table(name = "bus_unavailability")
public class BusUnavailability {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "bus_unavailability_seq")
    @SequenceGenerator(
            name = "bus_unavailability_seq",
            sequenceName = "bus_unavailability_seq",
            allocationSize = 50)
    private Long id;

    @Column(name = "bus_id", nullable = false)
    private Long busId;

    @Column(name = "starts_at", nullable = false)
    private Instant startsAt;

    @Column(name = "ends_at", nullable = false)
    private Instant endsAt;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private UnavailabilityReason reason;

    private String note;

    @Column(name = "created_at", nullable = false, insertable = false, updatable = false)
    private Instant createdAt;

    protected BusUnavailability() {
        // for JPA
    }

    public BusUnavailability(Long busId, Instant startsAt, Instant endsAt, UnavailabilityReason reason, String note) {
        if (!endsAt.isAfter(startsAt)) {
            throw new IllegalArgumentException("unavailability must end after it starts");
        }
        this.busId = busId;
        this.startsAt = startsAt;
        this.endsAt = endsAt;
        this.reason = reason;
        this.note = note;
    }

    /** Half-open comparison, matching the '[)' bounds of the generated range column. */
    public boolean overlaps(Instant from, Instant to) {
        return startsAt.isBefore(to) && endsAt.isAfter(from);
    }

    public Long getId() {
        return id;
    }

    public Long getBusId() {
        return busId;
    }

    public Instant getStartsAt() {
        return startsAt;
    }

    public Instant getEndsAt() {
        return endsAt;
    }

    public UnavailabilityReason getReason() {
        return reason;
    }

    public String getNote() {
        return note;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
