package com.dtc.transit.masterdata.stop;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;

import org.locationtech.jts.geom.Point;

import com.dtc.transit.common.jpa.BaseEntity;

/**
 * A boarding point.
 *
 * <p>Three flags matter to scheduling rather than to passengers. A terminal is where a bus lays over
 * between trips. A relief point is where one crew can hand a bus to another, which is what makes duty
 * cutting possible at all. Crew facilities decide whether a gap there can count as a break.
 */
@Entity
@Table(name = "stop")
public class Stop extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "stop_seq")
    @SequenceGenerator(name = "stop_seq", sequenceName = "stop_seq", allocationSize = 50)
    private Long id;

    @Column(nullable = false)
    private String code;

    @Column(nullable = false)
    private String name;

    @Column(columnDefinition = "geometry(Point,4326)", nullable = false)
    private Point location;

    /**
     * Projected copy, generated by the database.
     *
     * <p>Mapped read-only so that radius filters can compare metres against an indexed column. Writing
     * it from Java would duplicate the transform and risk the two columns disagreeing.
     */
    @Column(name = "location_utm", columnDefinition = "geometry(Point,32643)", insertable = false, updatable = false)
    private Point locationUtm;

    @Column(name = "is_terminal", nullable = false)
    private boolean terminal;

    @Column(name = "is_relief_point", nullable = false)
    private boolean reliefPoint;

    @Column(name = "has_crew_facilities", nullable = false)
    private boolean crewFacilities;

    @Column(nullable = false)
    private boolean active = true;

    protected Stop() {
        // for JPA
    }

    public Stop(String code, String name, Point location) {
        this.code = code;
        this.name = name;
        this.location = location;
    }

    public Long getId() {
        return id;
    }

    public String getCode() {
        return code;
    }

    public String getName() {
        return name;
    }

    public Point getLocation() {
        return location;
    }

    public Point getLocationUtm() {
        return locationUtm;
    }

    public boolean isTerminal() {
        return terminal;
    }

    public boolean isReliefPoint() {
        return reliefPoint;
    }

    public boolean hasCrewFacilities() {
        return crewFacilities;
    }

    public boolean isActive() {
        return active;
    }

    public void rename(String name) {
        this.name = name;
    }

    public void relocate(Point location) {
        this.location = location;
    }

    public void setFlags(boolean terminal, boolean reliefPoint, boolean crewFacilities) {
        this.terminal = terminal;
        this.reliefPoint = reliefPoint;
        this.crewFacilities = crewFacilities;
    }

    public void setActive(boolean active) {
        this.active = active;
    }
}
